#page title
page_title                                : WhatsFood                               # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :  https://wa.me/14155238886?text=I%20want%20to%20create%20a%20lunch%20group.                                            # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :  https://wa.me/14155238886?text=I%20want%20to%20create%20a%20lunch%20group.                                         # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : WhatsFood                               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Automatic food orders for groups.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                 
your_link                                 :                      
your_city                                 : Berlin                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : cshubhamrao/WhatsFood
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Automatic Group Orders
    description                           : From large to small groups, order food the smart way.   
    fontawesome_icon_name                 : users
    
  - title                                 : Recurring
    description                           : Fire-and-forget, set up once and enjoy the daily group orders. 
    fontawesome_icon_name                 : history

  - title                                 : Reminders
    description                           : Gentle, private reminders to members who haven't replied automatically done.
    fontawesome_icon_name                 : play-circle

  - title                                 : Restaurant Picker (soon)
    description                           : Making it fun to decide on a restaurant as a group. 
    fontawesome_icon_name                 : map-marker-alt

  - title                                 : Automatic Order (soon)
    description                           : Integration with major delivery networks avoid manual & error prone re-entry of the order.
    fontawesome_icon_name                 : magic

  - title                                 : Payments & Splitting (soon)
    description                           : Fully integrated payments including the nasty part to split the bill according to orders.
    fontawesome_icon_name                 : credit-card

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/group-of-people-making-toast-3184183.jpg # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#365aa1"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#365aa1"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
